server:
  port: 8087
spring:
  application:
    name: users
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:5432/postgres?currentSchema=cinema_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

